// Columnas centralizadas del Reporte Maestro: una sola lista para las 4 áreas
// (Tienda/Foráneo/Domicilio/Página). Cuando un concepto existe en más de un
// origen (ej. Cliente, Surtidor, Se Entregó) comparten la misma columna;
// cuando es propio de un solo origen (ej. Paquetería, Empacador, Factura) se
// deja igual y queda "N/A" en las filas de las áreas donde no aplica -- ver
// useReporteMaestro.js (NA_ROW / mapTiendaRow / mapForaneoRow / mapPaginaRow).
export const MAESTRO_FIELDS = {
  area: 'Área',
  turn: 'Turno',
  name: 'Cliente',
  pedido_web: 'Pedido Web',
  erp_order: 'Pedido',
  erp_order_count: 'Conteo de pedidos',
  agregados: 'Agregados',
  quantity: 'Cantidad',
  asesor: 'Asesor',
  tipo_pedidos: 'Tipo pedidos',
  status_label: 'Estado Final',
  current_status: 'Estatus Actual',
  paqueteria: 'Paquetería',
  guia: 'Guía',
  factura: 'Factura',
  regimen: 'Régimen',
  uso_cfdi: 'Uso CFDI',
  facturado_por: 'Facturado Por',
  comentarios: 'Comentarios',
  comprobante_pago: 'Comprobante de Pago',
  incidencias: 'Incidencias',
  incidencias_agentes: 'Agente con Incidencia',
  solucion_aplicada: 'Solución Aplicada',
  llego: 'Llegó',
  registro_turno: 'Registró Turno',
  atendio_piso: 'Lo atendió piso',
  se_creo_pedido: 'Se creó el pedido',
  atendio_cajas: 'Lo atendió cajas',
  envio_transferencia: 'Se envió a Transferencia',
  finalizo_pago: 'Finalizó el Pago',
  empezo_surtir: 'Se Empezó a surtir',
  se_surtio: 'Se Surtió',
  surtidor: 'Surtidor',
  empacador: 'Empacador',
  se_empaco: 'Se Empacó',
  despachador: 'Despachador',
  asigno_entrega: 'Asignó la Entrega',
  se_entrego: 'Se Entregó',
  lo_entrego: 'Lo Entregó',
  se_cancelo: 'Se Canceló',
  razon_cancelacion: 'Razón de Cancelación',
  motivo_pausa: 'Motivo Pausa',
  lo_pauso: 'Lo pausó',
  tiempo_atencion_piso: 'Tiempo para atención de piso',
  tiempo_creacion_pedido: 'Tiempo de creación del pedido',
  tiempo_atencion_cajas: 'Tiempo para atención en cajas',
  tiempo_transferencia: 'Tiempo en Transferencia',
  tiempo_pago: 'Tiempo de Pago',
  tiempo_recibir_pedido: 'Tiempo en Recibir pedido',
  tiempo_atencion_almacen: 'Tiempo para atención por Almacén',
  tiempo_surtir: 'Tiempo para surtir',
  tiempo_empacar: 'Tiempo para Empacar',
  tiempo_entregar: 'Tiempo para Entregar',
  tiempo_entrega: 'Tiempo de entrega',
  tiempo_facturar: 'Tiempo para Facturar',
  tiempo_piso: 'Tiempo en Piso',
  tiempo_cajas: 'Tiempo en Cajas',
  tiempo_almacen: 'Tiempo en Almacén',
  tiempo_tienda: 'Tiempo en Tienda',
  tiempo_pausado: 'Tiempo Pausado',
  tiempo_total: 'Tiempo Total',
  clasificacion: 'Clasificación',
  fecha: 'Fecha',
}
