export const PEDIDOS_PAGINA_FIELDS = {
  fecha: 'Fecha',
  erp_order_id: 'Pedido',
  id: 'Pedido Web',
  customer: 'Cliente',
  total: 'Monto',
  quantity_total: 'Piezas',
  shipping_type: 'Tipo Envío',
  current_status: 'Estatus Actual',
  status_final: 'Estatus Final',
  time_paid_at: 'Pagado',
  surtidor: 'Surtidor',
  time_surtido_start: 'Inicio Surtido',
  time_surtido_end: 'Fin Surtido',
  diff_surtiendo: 'Tiempo Surtiendo',
  incomplete_reason: 'Razón Incompleto',
  solution: 'Solución Aplicada',
  despachador: 'Despachador',
  time_despachado_at: 'Despachado',
  diff_despacho: 'Tiempo para Despacho',
  empacador: 'Empacador',
  time_empacado_at: 'Empacado',
  diff_empaque: 'Tiempo para Empaque',
  comprobante_estado: 'Comprobante de Pago',
  Facturador: 'Facturador',
  time_facturado_at: 'Facturado',
  diff_caja: 'Tiempo en Caja',
  entregador: 'Entregó',
  time_entregado_at: 'Entregado',
  diff_entrega: 'Tiempo de Entrega',
  diff_total: 'Tiempo Total (Pago → Entrega)',
  guia_numbers: 'Guía(s)',
}
